Citizen.CreateThread(function()
	local blip = AddBlipForCoord(-275.522, 6635.835, 7.425)
	SetBlipSprite(blip, 304)
	SetBlipDisplay(blip, 4)
	SetBlipScale(blip, 1.0)
	SetBlipColour(blip, 5)
	SetBlipAsShortRange(blip, false)
	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Weazel News Van")
	EndTextCommandSetBlipName(blip)
end)